version = 0.1
[dev.deploy.parameters]
stack_name = "dev-jantools-api-v2"
resolve_s3 = true
s3_prefix = "dev-jantools-api-v2"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"dev\""
image_repositories = ["Jantools=767397921354.dkr.ecr.ap-northeast-1.amazonaws.com/jantools-api-v2-repo"]

[prod.deploy.parameters]
stack_name = "prod-jantools-api-v2"
resolve_s3 = true
s3_prefix = "prod-jantools-api-v2"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"prod\""
image_repositories = ["Jantools=767397921354.dkr.ecr.ap-northeast-1.amazonaws.com/jantools-api-v2-repo"]