version = 0.1
[dev.deploy.parameters]
stack_name = "go-rest-template-dev"
resolve_s3 = true
s3_prefix = ""
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""

[prod.deploy.parameters]
stack_name = "go-rest-template-prod"
resolve_s3 = true
s3_prefix = ""
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""