AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: jantoolsAPIv2

Globals:
  Function:
    Timeout: 50
    MemorySize: 512

Parameters:
  ENV:
    Type: String
    Default: 'dev'
  JWT_SECRET:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/jantools-v2-api/jwt-secret

Resources:
  JantoolsAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ENV
      OpenApiVersion: 3.0.1
  Jantools:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ENV}_jantool_api_v2'
      PackageType: Image
      Architectures:
        - x86_64
      Role: arn:aws:iam::767397921354:role/jantools-api-v2-lambda
      Environment:
        Variables:
          ENV: !Ref ENV
          JWT_SECRET: !Ref JWT_SECRET
      Events:
        ApiGwEndPointRoot:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref JantoolsAPIGateway
        ApiGwEndPoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref JantoolsAPIGateway
    Metadata:
      DockerTag: go-1.23.1
      DockerContext: ./scripts
      Dockerfile: Dockerfile
      DockerBuildTarget: prod
  LeagueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ENV}_league' 
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  GameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ENV}_game' 
      AttributeDefinitions:
        - AttributeName: league_id
          AttributeType: S
        - AttributeName: id  
          AttributeType: S        
      KeySchema:
        - AttributeName: league_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1