AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: jantoolsAPIv2

Globals:
  Function:
    Timeout: 5
    MemorySize: 256

Parameters:
  ENV:
    Type: String
    Default: 'dev'

Resources:
  JantoolsAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ENV
  Jantools:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'JantoolsAPI_${ENV}'
      PackageType: Image
      Architectures:
        - x86_64
      # Role: #role
      Environment:
        Variables:
          ENV: !Ref ENV
      Events:
        ApiGwEndPointRoot:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref JantoolsAPIGateway
        ApiGwEndPoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref JantoolsAPIGateway
    Metadata:
      DockerTag: provided.al2-v1
      DockerContext: ./scripts
      Dockerfile: Dockerfile
      DockerBuildTarget: prod