services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - jantools-network
  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    networks:
      - jantools-network
  go:
    container_name: jantools-api-v2
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    tty: true
    environment: 
      ENV: local
      AWS_REGION : ap-northeast-1
      JWT_SECRET : secret
    networks:
      - jantools-network
networks:
  jantools-network:
    driver: bridge